/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pregnancydiary.views;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author michaelannor
 */
public class LoginForm extends javax.swing.JFrame {
        
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    //accessors: text boxes, labels and buttons
   public JButton getSignInLoginBtn(){
        return signinBtn_Login;
    }
   /**
    * Accessor to return the signup clickable label on the login screen
    * @return Clickable signup label
    */
   public JLabel getSignUpLoginBtn(){
        return signupLabel_Login;
    }
   /**
    * Accessor method to get the username text field
    * @return username text field
    */
   public JTextField getUsernameText_Login(){
         return usernameText_Login;
     }
   
   /**
    * Accessor method to return the password field
    * @return Password field
    */
   public JPasswordField getPasswordText_Login(){
         return passwordText_Login;
     }
    /**
     * Accessor method to return the Error Dialog
     * @return Error Dialog
     */
   public JDialog getError(){
       error.setLocationRelativeTo(null);
       return error;
   }
   /**
    * Accessor method to return the error dialog okay button
    * @return error dialog okay button
    */
   public JButton getErrorOkayBtn(){
       return errorOkayBtn;
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        errorOkayBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginCoverPanel = new javax.swing.JPanel();
        titleLabel_Login = new javax.swing.JLabel();
        subTitleLabel_Login = new javax.swing.JLabel();
        iconLabel_Login = new javax.swing.JLabel();
        usernamePanel = new javax.swing.JPanel();
        usernameText_Login = new javax.swing.JTextField();
        usernameLabel_Login = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        passwordText_Login = new javax.swing.JPasswordField();
        passwordLabel_Login = new javax.swing.JLabel();
        signinPanel = new javax.swing.JPanel();
        signupLabel_Login = new javax.swing.JLabel();
        signinBtn_Login = new javax.swing.JButton();

        error.setModal(true);
        error.setResizable(false);
        error.setSize(new java.awt.Dimension(488, 208));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 107, 221));
        jLabel1.setText("Invalid combination of username and password.");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pregnancydiary/images/dialog_icon_blue.png"))); // NOI18N

        errorOkayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pregnancydiary/images/ok_btn_small.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 107, 221));
        jLabel2.setText("Error:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorOkayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(errorOkayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout errorLayout = new javax.swing.GroupLayout(error.getContentPane());
        error.getContentPane().setLayout(errorLayout);
        errorLayout.setHorizontalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        errorLayout.setVerticalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        loginCoverPanel.setBackground(new java.awt.Color(42, 107, 221));

        titleLabel_Login.setFont(new java.awt.Font("San Francisco Display", 1, 24)); // NOI18N
        titleLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel_Login.setText("Pregnancy Diary");

        subTitleLabel_Login.setFont(new java.awt.Font("San Francisco Display", 0, 20)); // NOI18N
        subTitleLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        subTitleLabel_Login.setText("Welcome to the");

        iconLabel_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pregnancydiary/images/cover.png"))); // NOI18N

        javax.swing.GroupLayout loginCoverPanelLayout = new javax.swing.GroupLayout(loginCoverPanel);
        loginCoverPanel.setLayout(loginCoverPanelLayout);
        loginCoverPanelLayout.setHorizontalGroup(
            loginCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCoverPanelLayout.createSequentialGroup()
                .addGroup(loginCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginCoverPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(iconLabel_Login))
                    .addGroup(loginCoverPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(subTitleLabel_Login))
                    .addGroup(loginCoverPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(titleLabel_Login)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        loginCoverPanelLayout.setVerticalGroup(
            loginCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCoverPanelLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(iconLabel_Login)
                .addGap(35, 35, 35)
                .addComponent(subTitleLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titleLabel_Login)
                .addGap(61, 61, 61))
        );

        usernamePanel.setBackground(new java.awt.Color(255, 255, 255));

        usernameLabel_Login.setText("Username:");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(usernameLabel_Login)
                .addGap(18, 18, 18)
                .addComponent(usernameText_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(usernameText_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addComponent(usernameLabel_Login))
        );

        passwordPanel.setBackground(new java.awt.Color(255, 255, 255));

        passwordText_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordText_LoginActionPerformed(evt);
            }
        });

        passwordLabel_Login.setText("Password:");

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(passwordLabel_Login)
                .addGap(18, 18, 18)
                .addComponent(passwordText_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(passwordLabel_Login))
                .addContainerGap())
        );

        signinPanel.setBackground(new java.awt.Color(255, 255, 255));

        signupLabel_Login.setFont(new java.awt.Font("San Francisco Display", 0, 14)); // NOI18N
        signupLabel_Login.setForeground(new java.awt.Color(42, 107, 221));
        signupLabel_Login.setText("New? Sign up Here!");
        signupLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabel_LoginMouseClicked(evt);
            }
        });

        signinBtn_Login.setBackground(new java.awt.Color(255, 255, 255));
        signinBtn_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pregnancydiary/images/login_unselect.png"))); // NOI18N
        signinBtn_Login.setBorderPainted(false);
        signinBtn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinBtn_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signinPanelLayout = new javax.swing.GroupLayout(signinPanel);
        signinPanel.setLayout(signinPanelLayout);
        signinPanelLayout.setHorizontalGroup(
            signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPanelLayout.createSequentialGroup()
                .addGroup(signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(signinBtn_Login))
                    .addGroup(signinPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(signupLabel_Login)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signinPanelLayout.setVerticalGroup(
            signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPanelLayout.createSequentialGroup()
                .addComponent(signinBtn_Login)
                .addGap(12, 12, 12)
                .addComponent(signupLabel_Login)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(loginCoverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(loginCoverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordText_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordText_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordText_LoginActionPerformed

    private void signinBtn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtn_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinBtn_LoginActionPerformed

    private void signupLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabel_LoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signupLabel_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog error;
    private javax.swing.JButton errorOkayBtn;
    private javax.swing.JLabel iconLabel_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loginCoverPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel passwordLabel_Login;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPasswordField passwordText_Login;
    private javax.swing.JButton signinBtn_Login;
    private javax.swing.JPanel signinPanel;
    private javax.swing.JLabel signupLabel_Login;
    private javax.swing.JLabel subTitleLabel_Login;
    private javax.swing.JLabel titleLabel_Login;
    private javax.swing.JLabel usernameLabel_Login;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JTextField usernameText_Login;
    // End of variables declaration//GEN-END:variables
}
