/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pregnancydiary.views;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author michaelannor
 */
public class SignupForm extends javax.swing.JFrame {
        
    /**
     * Creates new form LoginForm
     */
    public SignupForm() {
        initComponents();
                setLocationRelativeTo(null);

    }

    //accessors: text boxes, labels and buttons
    /**
     * Accessor to get the signup button
     * @return Signup Button
     */
   public JButton getSignUpSignupBtn(){
        return signupBtn_Signup;
    }
   /**
    * Accessor to get the username text field
    * @return Username Text Field
    */
   public JTextField getUsernameText_Signup(){
         return usernameText_Signup;
     }
   
   /**
    * Accessor to get the first name text field
    * @return first name text field
    */
   public JTextField getFirstNameText_Signup(){
         return firstNameText_Signup;
     }
   /**
    * Accessor to get the surname text field
    * @return surname text field
    */
   public JTextField getSurnameText_Signup(){
         return surnameText_Signup;
     }
   /**
    * Accessor method to get the hospital text field
    * @return hospital text field
    */
   public JTextField getHospitalText_Signup(){
         return hospitalText_Signup;
     }
   /**
    * Accessor method to get the password text field
    * @return password text field
    */
   public JPasswordField getPasswordText_Signup(){
         return passwordText_Signup;
     }
   /**
    * Accessor method to get the date of birth date chooser
    * @return date of birth date chooser
    */
   public JDateChooser getDobDateChooser_Signup(){
         return dobDateChooser_Signup;
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupPanel = new javax.swing.JPanel();
        signupCoverPanel = new javax.swing.JPanel();
        titleLabel_Signup = new javax.swing.JLabel();
        iconLabel_Signup = new javax.swing.JLabel();
        firstNamePanel = new javax.swing.JPanel();
        firstNameText_Signup = new javax.swing.JTextField();
        firstNameLabel_Signup = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        passwordText_Signup = new javax.swing.JPasswordField();
        passwordLabel_Signup = new javax.swing.JLabel();
        signupBtnPanel = new javax.swing.JPanel();
        signupBtn_Signup = new javax.swing.JButton();
        surnamePanel = new javax.swing.JPanel();
        surnameText_Signup = new javax.swing.JTextField();
        surnameLabel_Signup = new javax.swing.JLabel();
        hospitalPanel = new javax.swing.JPanel();
        hospitalText_Signup = new javax.swing.JTextField();
        hospitalLabel_Signup = new javax.swing.JLabel();
        usernamePanel = new javax.swing.JPanel();
        usernameText_Signup = new javax.swing.JTextField();
        usernameLabel_Signup = new javax.swing.JLabel();
        dobPanel = new javax.swing.JPanel();
        dobLabel_Signup = new javax.swing.JLabel();
        dobDateChooser_Signup = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        signupPanel.setBackground(new java.awt.Color(255, 255, 255));
        signupPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        signupCoverPanel.setBackground(new java.awt.Color(42, 107, 221));

        titleLabel_Signup.setFont(new java.awt.Font("San Francisco Display", 1, 24)); // NOI18N
        titleLabel_Signup.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel_Signup.setText("Sign Up");

        iconLabel_Signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pregnancydiary/images/cover.png"))); // NOI18N

        javax.swing.GroupLayout signupCoverPanelLayout = new javax.swing.GroupLayout(signupCoverPanel);
        signupCoverPanel.setLayout(signupCoverPanelLayout);
        signupCoverPanelLayout.setHorizontalGroup(
            signupCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupCoverPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconLabel_Signup)
                .addGap(67, 67, 67)
                .addComponent(titleLabel_Signup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupCoverPanelLayout.setVerticalGroup(
            signupCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupCoverPanelLayout.createSequentialGroup()
                .addGroup(signupCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupCoverPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconLabel_Signup))
                    .addGroup(signupCoverPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(titleLabel_Signup)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        firstNamePanel.setBackground(new java.awt.Color(255, 255, 255));

        firstNameLabel_Signup.setText("First Name");

        javax.swing.GroupLayout firstNamePanelLayout = new javax.swing.GroupLayout(firstNamePanel);
        firstNamePanel.setLayout(firstNamePanelLayout);
        firstNamePanelLayout.setHorizontalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNamePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(firstNameLabel_Signup)
                .addGap(18, 18, 18)
                .addComponent(firstNameText_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        firstNamePanelLayout.setVerticalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(firstNameText_Signup, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addComponent(firstNameLabel_Signup))
        );

        passwordPanel.setBackground(new java.awt.Color(255, 255, 255));

        passwordText_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordText_SignupActionPerformed(evt);
            }
        });

        passwordLabel_Signup.setText("Password:");

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(passwordLabel_Signup)
                .addGap(28, 28, 28)
                .addComponent(passwordText_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText_Signup, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(passwordLabel_Signup))
                .addContainerGap())
        );

        signupBtnPanel.setBackground(new java.awt.Color(255, 255, 255));

        signupBtn_Signup.setBackground(new java.awt.Color(255, 255, 255));
        signupBtn_Signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pregnancydiary/images/Signup_unselect.png"))); // NOI18N
        signupBtn_Signup.setBorderPainted(false);
        signupBtn_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtn_SignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupBtnPanelLayout = new javax.swing.GroupLayout(signupBtnPanel);
        signupBtnPanel.setLayout(signupBtnPanelLayout);
        signupBtnPanelLayout.setHorizontalGroup(
            signupBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupBtnPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(signupBtn_Signup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupBtnPanelLayout.setVerticalGroup(
            signupBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupBtnPanelLayout.createSequentialGroup()
                .addComponent(signupBtn_Signup)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        surnamePanel.setBackground(new java.awt.Color(255, 255, 255));

        surnameLabel_Signup.setText("Surname:");

        javax.swing.GroupLayout surnamePanelLayout = new javax.swing.GroupLayout(surnamePanel);
        surnamePanel.setLayout(surnamePanelLayout);
        surnamePanelLayout.setHorizontalGroup(
            surnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surnamePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(surnameLabel_Signup)
                .addGap(31, 31, 31)
                .addComponent(surnameText_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        surnamePanelLayout.setVerticalGroup(
            surnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(surnameText_Signup, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addComponent(surnameLabel_Signup))
        );

        hospitalPanel.setBackground(new java.awt.Color(255, 255, 255));

        hospitalLabel_Signup.setText("Hospital:");

        javax.swing.GroupLayout hospitalPanelLayout = new javax.swing.GroupLayout(hospitalPanel);
        hospitalPanel.setLayout(hospitalPanelLayout);
        hospitalPanelLayout.setHorizontalGroup(
            hospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(hospitalLabel_Signup)
                .addGap(34, 34, 34)
                .addComponent(hospitalText_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hospitalPanelLayout.setVerticalGroup(
            hospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hospitalText_Signup, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addComponent(hospitalLabel_Signup))
        );

        usernamePanel.setBackground(new java.awt.Color(255, 255, 255));

        usernameLabel_Signup.setText("Username:");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(usernameLabel_Signup)
                .addGap(27, 27, 27)
                .addComponent(usernameText_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(usernameText_Signup, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addComponent(usernameLabel_Signup))
        );

        dobPanel.setBackground(new java.awt.Color(255, 255, 255));

        dobLabel_Signup.setText("Date of Birth:");

        javax.swing.GroupLayout dobPanelLayout = new javax.swing.GroupLayout(dobPanel);
        dobPanel.setLayout(dobPanelLayout);
        dobPanelLayout.setHorizontalGroup(
            dobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dobPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(dobLabel_Signup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dobDateChooser_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dobPanelLayout.setVerticalGroup(
            dobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dobPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dobLabel_Signup)
                .addGap(15, 15, 15))
            .addGroup(dobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dobDateChooser_Signup, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout signupPanelLayout = new javax.swing.GroupLayout(signupPanel);
        signupPanel.setLayout(signupPanelLayout);
        signupPanelLayout.setHorizontalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(surnamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hospitalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dobPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addComponent(signupBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(signupCoverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        signupPanelLayout.setVerticalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addComponent(signupCoverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(firstNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(surnamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(dobPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(hospitalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(signupBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordText_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordText_SignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordText_SignupActionPerformed

    private void signupBtn_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtn_SignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupBtn_SignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dobDateChooser_Signup;
    private javax.swing.JLabel dobLabel_Signup;
    private javax.swing.JPanel dobPanel;
    private javax.swing.JLabel firstNameLabel_Signup;
    private javax.swing.JPanel firstNamePanel;
    private javax.swing.JTextField firstNameText_Signup;
    private javax.swing.JLabel hospitalLabel_Signup;
    private javax.swing.JPanel hospitalPanel;
    private javax.swing.JTextField hospitalText_Signup;
    private javax.swing.JLabel iconLabel_Signup;
    private javax.swing.JLabel passwordLabel_Signup;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPasswordField passwordText_Signup;
    private javax.swing.JPanel signupBtnPanel;
    private javax.swing.JButton signupBtn_Signup;
    private javax.swing.JPanel signupCoverPanel;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JLabel surnameLabel_Signup;
    private javax.swing.JPanel surnamePanel;
    private javax.swing.JTextField surnameText_Signup;
    private javax.swing.JLabel titleLabel_Signup;
    private javax.swing.JLabel usernameLabel_Signup;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JTextField usernameText_Signup;
    // End of variables declaration//GEN-END:variables
}
